'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace Kredit
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="svcKreditSoap", [Namespace]:="http://tempuri.org/KatalaWebServices/svcKredit")>  _
    Public Class svcKredit
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("Katala.Kredit.svcKredit")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/KatalaWebServices/svcKredit.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KatalaWebServices/svcKredit/GetLastRegisterNumber", RequestNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", ResponseNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLastRegisterNumber(ByVal dtDate As Date, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetLastRegisterNumber", New Object() {dtDate, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetLastRegisterNumber(ByVal dtDate As Date, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLastRegisterNumber", New Object() {dtDate, strAPP_ID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetLastRegisterNumber(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KatalaWebServices/svcKredit/GetKreditRegistration", RequestNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", ResponseNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetKreditRegistration(ByVal strMembershipId As String, ByVal strRegPeriod As String, ByVal strKreditType As String, ByVal strLoanId As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetKreditRegistration", New Object() {strMembershipId, strRegPeriod, strKreditType, strLoanId, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetKreditRegistration(ByVal strMembershipId As String, ByVal strRegPeriod As String, ByVal strKreditType As String, ByVal strLoanId As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetKreditRegistration", New Object() {strMembershipId, strRegPeriod, strKreditType, strLoanId, strAPP_ID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetKreditRegistration(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KatalaWebServices/svcKredit/GetKreditRegistrationDetail", RequestNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", ResponseNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetKreditRegistrationDetail(ByVal strLoanId As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetKreditRegistrationDetail", New Object() {strLoanId, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetKreditRegistrationDetail(ByVal strLoanId As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetKreditRegistrationDetail", New Object() {strLoanId, strAPP_ID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetKreditRegistrationDetail(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KatalaWebServices/svcKredit/AddKreditRegistration", RequestNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", ResponseNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddKreditRegistration(ByVal adoDS As System.Data.DataSet, ByVal strApp_id As String) As Object
            Dim results() As Object = Me.Invoke("AddKreditRegistration", New Object() {adoDS, strApp_id})
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        Public Function BeginAddKreditRegistration(ByVal adoDS As System.Data.DataSet, ByVal strApp_id As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddKreditRegistration", New Object() {adoDS, strApp_id}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddKreditRegistration(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KatalaWebServices/svcKredit/ModifyKreditRegistration", RequestNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", ResponseNamespace:="http://tempuri.org/KatalaWebServices/svcKredit", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ModifyKreditRegistration(ByVal adoDS As System.Data.DataSet, ByVal strApp_id As String) As Object
            Dim results() As Object = Me.Invoke("ModifyKreditRegistration", New Object() {adoDS, strApp_id})
            Return CType(results(0),Object)
        End Function
        
        '<remarks/>
        Public Function BeginModifyKreditRegistration(ByVal adoDS As System.Data.DataSet, ByVal strApp_id As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ModifyKreditRegistration", New Object() {adoDS, strApp_id}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndModifyKreditRegistration(ByVal asyncResult As System.IAsyncResult) As Object
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object)
        End Function
    End Class
End Namespace
