'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace HouseKeeping
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="svcHouseKeepingSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class svcHouseKeeping
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetResourceTypeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetResourceCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetResourceCodeDetailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddNewResourceCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteResourceCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateResourceCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetWarehouseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSystemDateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAcctPeriodOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetResourceCodeType1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/KatalaWebServices/svcHouseKeeping.Asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetResourceTypeCompleted As GetResourceTypeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetResourceCodeCompleted As GetResourceCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetResourceCodeDetailCompleted As GetResourceCodeDetailCompletedEventHandler
        
        '''<remarks/>
        Public Event AddNewResourceCodeCompleted As AddNewResourceCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteResourceCodeCompleted As DeleteResourceCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateResourceCodeCompleted As UpdateResourceCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetWarehouseCompleted As GetWarehouseCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSystemDateCompleted As GetSystemDateCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAcctPeriodCompleted As GetAcctPeriodCompletedEventHandler
        
        '''<remarks/>
        Public Event GetResourceCodeType1Completed As GetResourceCodeType1CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetResourceType", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetResourceType(ByVal strProgramId As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetResourceType", New Object() {strProgramId, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetResourceType(ByVal strProgramId As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetResourceType", New Object() {strProgramId, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetResourceType(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetResourceTypeAsync(ByVal strProgramId As String, ByVal strAPP_ID As String)
            Me.GetResourceTypeAsync(strProgramId, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetResourceTypeAsync(ByVal strProgramId As String, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetResourceTypeOperationCompleted Is Nothing) Then
                Me.GetResourceTypeOperationCompleted = AddressOf Me.OnGetResourceTypeOperationCompleted
            End If
            Me.InvokeAsync("GetResourceType", New Object() {strProgramId, strAPP_ID}, Me.GetResourceTypeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetResourceTypeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetResourceTypeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetResourceTypeCompleted(Me, New GetResourceTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetResourceCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetResourceCode(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetResourceCode", New Object() {strProgramId, strResourceType, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetResourceCode(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetResourceCode", New Object() {strProgramId, strResourceType, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetResourceCode(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetResourceCodeAsync(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strAPP_ID As String)
            Me.GetResourceCodeAsync(strProgramId, strResourceType, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetResourceCodeAsync(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetResourceCodeOperationCompleted Is Nothing) Then
                Me.GetResourceCodeOperationCompleted = AddressOf Me.OnGetResourceCodeOperationCompleted
            End If
            Me.InvokeAsync("GetResourceCode", New Object() {strProgramId, strResourceType, strAPP_ID}, Me.GetResourceCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetResourceCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetResourceCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetResourceCodeCompleted(Me, New GetResourceCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetResourceCodeDetail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetResourceCodeDetail(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetResourceCodeDetail", New Object() {strProgramId, strResourceType, strResourceCode, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetResourceCodeDetail(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetResourceCodeDetail", New Object() {strProgramId, strResourceType, strResourceCode, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetResourceCodeDetail(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetResourceCodeDetailAsync(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String)
            Me.GetResourceCodeDetailAsync(strProgramId, strResourceType, strResourceCode, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetResourceCodeDetailAsync(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetResourceCodeDetailOperationCompleted Is Nothing) Then
                Me.GetResourceCodeDetailOperationCompleted = AddressOf Me.OnGetResourceCodeDetailOperationCompleted
            End If
            Me.InvokeAsync("GetResourceCodeDetail", New Object() {strProgramId, strResourceType, strResourceCode, strAPP_ID}, Me.GetResourceCodeDetailOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetResourceCodeDetailOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetResourceCodeDetailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetResourceCodeDetailCompleted(Me, New GetResourceCodeDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewResourceCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddNewResourceCode(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String) As String
            Dim results() As Object = Me.Invoke("AddNewResourceCode", New Object() {adoDS, strAPP_ID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginAddNewResourceCode(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddNewResourceCode", New Object() {adoDS, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAddNewResourceCode(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddNewResourceCodeAsync(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String)
            Me.AddNewResourceCodeAsync(adoDS, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddNewResourceCodeAsync(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.AddNewResourceCodeOperationCompleted Is Nothing) Then
                Me.AddNewResourceCodeOperationCompleted = AddressOf Me.OnAddNewResourceCodeOperationCompleted
            End If
            Me.InvokeAsync("AddNewResourceCode", New Object() {adoDS, strAPP_ID}, Me.AddNewResourceCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddNewResourceCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddNewResourceCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddNewResourceCodeCompleted(Me, New AddNewResourceCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteResourceCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DeleteResourceCode(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String)
            Me.Invoke("DeleteResourceCode", New Object() {strProgramId, strResourceType, strResourceCode, strAPP_ID})
        End Sub
        
        '''<remarks/>
        Public Function BeginDeleteResourceCode(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteResourceCode", New Object() {strProgramId, strResourceType, strResourceCode, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndDeleteResourceCode(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteResourceCodeAsync(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String)
            Me.DeleteResourceCodeAsync(strProgramId, strResourceType, strResourceCode, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteResourceCodeAsync(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strResourceCode As String, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.DeleteResourceCodeOperationCompleted Is Nothing) Then
                Me.DeleteResourceCodeOperationCompleted = AddressOf Me.OnDeleteResourceCodeOperationCompleted
            End If
            Me.InvokeAsync("DeleteResourceCode", New Object() {strProgramId, strResourceType, strResourceCode, strAPP_ID}, Me.DeleteResourceCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteResourceCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteResourceCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteResourceCodeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateResourceCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateResourceCode(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String)
            Me.Invoke("UpdateResourceCode", New Object() {adoDS, strAPP_ID})
        End Sub
        
        '''<remarks/>
        Public Function BeginUpdateResourceCode(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateResourceCode", New Object() {adoDS, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndUpdateResourceCode(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateResourceCodeAsync(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String)
            Me.UpdateResourceCodeAsync(adoDS, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateResourceCodeAsync(ByVal adoDS As System.Data.DataSet, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.UpdateResourceCodeOperationCompleted Is Nothing) Then
                Me.UpdateResourceCodeOperationCompleted = AddressOf Me.OnUpdateResourceCodeOperationCompleted
            End If
            Me.InvokeAsync("UpdateResourceCode", New Object() {adoDS, strAPP_ID}, Me.UpdateResourceCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateResourceCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateResourceCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateResourceCodeCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWarehouse", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetWarehouse(ByVal strDefault As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetWarehouse", New Object() {strDefault, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetWarehouse(ByVal strDefault As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetWarehouse", New Object() {strDefault, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetWarehouse(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetWarehouseAsync(ByVal strDefault As String, ByVal strAPP_ID As String)
            Me.GetWarehouseAsync(strDefault, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetWarehouseAsync(ByVal strDefault As String, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetWarehouseOperationCompleted Is Nothing) Then
                Me.GetWarehouseOperationCompleted = AddressOf Me.OnGetWarehouseOperationCompleted
            End If
            Me.InvokeAsync("GetWarehouse", New Object() {strDefault, strAPP_ID}, Me.GetWarehouseOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetWarehouseOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetWarehouseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetWarehouseCompleted(Me, New GetWarehouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSystemDate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSystemDate(ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetSystemDate", New Object() {strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetSystemDate(ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSystemDate", New Object() {strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetSystemDate(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSystemDateAsync(ByVal strAPP_ID As String)
            Me.GetSystemDateAsync(strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSystemDateAsync(ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetSystemDateOperationCompleted Is Nothing) Then
                Me.GetSystemDateOperationCompleted = AddressOf Me.OnGetSystemDateOperationCompleted
            End If
            Me.InvokeAsync("GetSystemDate", New Object() {strAPP_ID}, Me.GetSystemDateOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSystemDateOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSystemDateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSystemDateCompleted(Me, New GetSystemDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAcctPeriod", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAcctPeriod(ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetAcctPeriod", New Object() {strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetAcctPeriod(ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAcctPeriod", New Object() {strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAcctPeriod(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAcctPeriodAsync(ByVal strAPP_ID As String)
            Me.GetAcctPeriodAsync(strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAcctPeriodAsync(ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetAcctPeriodOperationCompleted Is Nothing) Then
                Me.GetAcctPeriodOperationCompleted = AddressOf Me.OnGetAcctPeriodOperationCompleted
            End If
            Me.InvokeAsync("GetAcctPeriod", New Object() {strAPP_ID}, Me.GetAcctPeriodOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAcctPeriodOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAcctPeriodCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAcctPeriodCompleted(Me, New GetAcctPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetResourceCodeType1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetResourceCodeType1(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strType1 As String, ByVal strAPP_ID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetResourceCodeType1", New Object() {strProgramId, strResourceType, strType1, strAPP_ID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetResourceCodeType1(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strType1 As String, ByVal strAPP_ID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetResourceCodeType1", New Object() {strProgramId, strResourceType, strType1, strAPP_ID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetResourceCodeType1(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetResourceCodeType1Async(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strType1 As String, ByVal strAPP_ID As String)
            Me.GetResourceCodeType1Async(strProgramId, strResourceType, strType1, strAPP_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetResourceCodeType1Async(ByVal strProgramId As String, ByVal strResourceType As String, ByVal strType1 As String, ByVal strAPP_ID As String, ByVal userState As Object)
            If (Me.GetResourceCodeType1OperationCompleted Is Nothing) Then
                Me.GetResourceCodeType1OperationCompleted = AddressOf Me.OnGetResourceCodeType1OperationCompleted
            End If
            Me.InvokeAsync("GetResourceCodeType1", New Object() {strProgramId, strResourceType, strType1, strAPP_ID}, Me.GetResourceCodeType1OperationCompleted, userState)
        End Sub
        
        Private Sub OnGetResourceCodeType1OperationCompleted(ByVal arg As Object)
            If (Not (Me.GetResourceCodeType1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetResourceCodeType1Completed(Me, New GetResourceCodeType1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetResourceTypeCompletedEventHandler(ByVal sender As Object, ByVal e As GetResourceTypeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetResourceTypeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetResourceCodeCompletedEventHandler(ByVal sender As Object, ByVal e As GetResourceCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetResourceCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetResourceCodeDetailCompletedEventHandler(ByVal sender As Object, ByVal e As GetResourceCodeDetailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetResourceCodeDetailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub AddNewResourceCodeCompletedEventHandler(ByVal sender As Object, ByVal e As AddNewResourceCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddNewResourceCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub DeleteResourceCodeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub UpdateResourceCodeCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetWarehouseCompletedEventHandler(ByVal sender As Object, ByVal e As GetWarehouseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetWarehouseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetSystemDateCompletedEventHandler(ByVal sender As Object, ByVal e As GetSystemDateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSystemDateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetAcctPeriodCompletedEventHandler(ByVal sender As Object, ByVal e As GetAcctPeriodCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAcctPeriodCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetResourceCodeType1CompletedEventHandler(ByVal sender As Object, ByVal e As GetResourceCodeType1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetResourceCodeType1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
